###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: zunme-memcached

#    redis:
#      image: redis:alpine
#      container_name: zunme-redis
    rabbitmq:
      image: "rabbitmq:3-management"
      container_name: zunme-rabbitmq 
      hostname: "rabbit1"
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
      ports:
        - "15672:15672"
        - "5672:5672"
      volumes:
        - "./conf/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
       
    mariadb:
      image: mariadb:10.1
      container_name: zunme-mariadb
      working_dir: /application
      volumes:
        - ./application:/application
      environment:
        - MYSQL_ROOT_PASSWORD=dlatjdtk
        - MYSQL_DATABASE=app01
        - MYSQL_USER=app01
        - MYSQL_PASSWORD=app01
      ports:
        - "8083:3306"

    webserver:
      image: nginx:alpine
      container_name: zunme-webserver
      working_dir: /application
      restart: always
      depends_on:
        - php-fpm
        - memcached
        - mariadb
        - rabbitmq
      volumes:
          - ./application:/application
          - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
       - "8443:443"

    php-fpm:
      #build: phpdocker/php-fpm
      image: zunme/php-default:7.2 
      container_name: zunme-php
      working_dir: /application
      volumes:
        - ./application:/application
        - ./conf/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
